# Generated by Django 2.2.7 on 2019-11-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_rate', models.PositiveIntegerField()),
                ('product_date', models.DateField(auto_now_add=True)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_rules', models.TextField()),
                ('product_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.Catagory')),
            ],
        ),
    ]
